"""Watcher sub-agent (FR-W1..W4).

Pulls spans created since the durable cursor, filters to candidate span trees,
emits Incidents. Invoked by the scheduled trace-poller (functions/trace_poller).
"""

from __future__ import annotations

from datetime import datetime, timezone

from .config import get_settings
from .events import bus
from .models import Incident, PipelineEvent, Stage
from .phoenix_mcp import PhoenixMCP
from .state import get_state


class Watcher:
    def __init__(self, mcp: PhoenixMCP | None = None) -> None:
        self.s = get_settings()
        self.mcp = mcp or PhoenixMCP(self.s)
        self.state = get_state()

    async def poll(self) -> list[Incident]:
        """One poll cycle. Returns fresh, not-yet-seen incidents (FR-W2/3/4, FR-L3).

        FEEDBACK-LOOP PROTECTION: TraceLog's replay, evaluator, and red-team stages
        all send messages to the Patient with session_id="test" and/or
        prompt_variant="candidate". These spans (plus their tool child spans) must be
        filtered out or the pipeline re-diagnoses its own test traffic forever.

        We filter on THREE signals:
        1. session_id == "test"  (explicit marker on replay/eval/red-team calls)
        2. prompt_variant == "candidate"  (replay/eval calls use a system_override)
        3. span_kind is a tool child span (no user-facing input, just tool I/O)
        """
        since = self.state.get_cursor()
        incidents: list[Incident] = []

        async with self.mcp.session() as phx:
            spans = await phx.query_spans(self.s.patient_project, since)

        newest = since
        for span in spans:
            if not span.span_id or self.state.seen(span.span_id):
                continue
            # --- feedback-loop filters ---
            if span.session_id == "test":
                self.state.mark_seen(span.span_id)  # mark seen so we never revisit
                continue
            # Skip spans generated by TraceLog's own replay/eval (prompt_variant=candidate)
            raw_attrs = span.raw.get("attributes", {})
            if isinstance(raw_attrs, str):
                import json as _json
                try:
                    raw_attrs = _json.loads(raw_attrs)
                except Exception:
                    raw_attrs = {}
            variant = _flat_attr(raw_attrs, "patient.prompt_variant")
            if variant == "candidate":
                self.state.mark_seen(span.span_id)
                continue
            # Skip tool child spans (they have no meaningful user input)
            span_kind = _flat_attr(raw_attrs, "openinference.span.kind")
            span_name = span.raw.get("name", "")
            if span_kind == "TOOL" or (isinstance(span_name, str) and span_name.startswith("tool.")):
                self.state.mark_seen(span.span_id)
                continue
            # --- end feedback-loop filters ---
            if not (span.input_text and span.output_text):
                continue  # FR-W3: only candidate LLM/tool trees
            inc = Incident.from_span(span)
            incidents.append(inc)
            await bus.publish(
                PipelineEvent(
                    incident_id=inc.incident_id,
                    stage=Stage.WATCHED,
                    title="New span observed",
                    detail=span.input_text[:160],
                    phoenix_url=self.mcp.span_url(span),
                )
            )
            if newest is None or span.started_at > newest:
                newest = span.started_at

        self.state.set_cursor(newest or datetime.now(timezone.utc))
        return incidents


def _flat_attr(attrs: dict, key: str) -> str:
    """Extract a dotted attribute from span attrs (flat or nested)."""
    val = attrs.get(key)
    if val is None and "." in key:
        val = attrs
        for part in key.split("."):
            if isinstance(val, dict):
                val = val.get(part)
            else:
                return ""
    return str(val) if val else ""
